My Documents/Aptana Studio 3 Workspace/Portfolio/config/routes.rb
Portfolio::Application.routes.draw do
resources :posts do
  resources :comments
end

  devise_for :users

 root :to =>'home#index'

end

My Documents/Aptana Studio 3 Workspace/Portfolio/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter, :user_id
  belongs_to :user
  
end

My Documents/Aptana Studio 3 Workspace/Portfolio/app/models/post.rb
class Post < ActiveRecord::Base
  scope :published, where(published: true)
  attr_accessible :content, :name, :title, :user_id, :tags_attributes
  
  validates :content,  :presence =>true, :length=>{:minimum =>50}
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
                    
                    has_many :comments, :dependent => :destroy
                    belongs_to :user
                    has_many :tags
                   
                   
    accepts_nested_attributes_for :tags , :allow_destroy =>true,
    :reject_if =>proc{ |attrs| attrs.all? {|k, v|v.blank?}}
 
                    
end

My Documents/Aptana Studio 3 Workspace/Portfolio/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :lasst_name, :profile_name
  
  # attr_accessible :title, :body
  has_many :posts
  has_many :comment
  
  def full_name
    first_name + " "+ lasst_name
  end
   
end

My Documents/Aptana Studio 3 Workspace/Portfolio/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
 
end

My Documents/Aptana Studio 3 Workspace/Portfolio/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end
  
    def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

end

My Documents/Aptana Studio 3 Workspace/Portfolio/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

My Documents/Aptana Studio 3 Workspace/Portfolio/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.published.paginate(:page => params[:page], :per_page =>1)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
     @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
      format.js
    end
  end
end

My Documents/Aptana Studio 3 Workspace/Portfolio/app/helpers/application_helper.rb
module ApplicationHelper
end

My Documents/Aptana Studio 3 Workspace/Portfolio/app/helpers/comments_helper.rb
module CommentsHelper
end

My Documents/Aptana Studio 3 Workspace/Portfolio/app/helpers/home_helper.rb
module HomeHelper
end

My Documents/Aptana Studio 3 Workspace/Portfolio/app/helpers/posts_helper.rb
module PostsHelper
 
  def join_tags(post)
    post.tags.map { |t| t.name }.join(", ")
  end

end

My Documents/Aptana Studio 3 Workspace/Portfolio/app/views/comments/_comment.html.erb
<h2>Comments</h2>
<% @post.comments.each do |comment| %>
  <p>
    <b>Commenter:</b>
    <%= comment.commenter %>
  </p>
 
  <p>
    <b>Comment:</b>
    <%= comment.body %>
  </p>
<% end %>
<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>

My Documents/Aptana Studio 3 Workspace/Portfolio/app/views/comments/_form.html.erb
<h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 
<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %> |

My Documents/Aptana Studio 3 Workspace/Portfolio/app/views/home/index.html.erb
<h2>Welcome</h2>
<div id="myCarousel" class="carousel slide">
	<ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="2"></li>
	</ol>
	<!-- Carousel items -->
	<div class="carousel-inner">
		<div class="active item">
			
			<%=image_tag("images.jpg")%>
		</div>
		<div class="item">
			<%=image_tag("images.jpg")%>
			<div class="caption">My captions</div>
		</div>
		<div class="item">
			<%=image_tag("images.jpg")%>
		</div>
	</div>
	<!-- Carousel nav -->
	<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

My Documents/Aptana Studio 3 Workspace/Portfolio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Portfolio</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<ul class="nav">
						<a class="brand">Portfolio</a>
						<li>
							<%= link_to "Browse",  posts_path%>
						</li>

					</ul>
					<ul class="nav pull-right">
						<% if user_signed_in? %>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
								<%="hi "+current_user.first_name %>
								
								<b class="caret"></b> </a>
							<ul class="dropdown-menu">
								<li>
									<a href="#">Profile</a>
								</li>
								<li>
									<a href="#">Edit</a>
								</li>
								<li>
									<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
								</li>
								<%else%>
								<li>
									<a href="#">Sign Up</a>
								</li>
								<li>
									<a href="#">Login</a>
								</li>
							</ul>
						</li>
						<%end%>
					</ul>
				</div>

			</div>

		</div>
		<div class="ribbon ">
			<div class="search">
				
			</div>

		</div>

		<!-- main content area-->
		<div class="container">
			<div class="span7 pull-left">

				<% if flash[:error] -%>
				<div class="alert">
					<button type="button" class="close" data-dismiss="alert">
						&times;
					</button>
					<p class='error'>
						<%= h flash[:error] %>
					</p>
				</div>

				<% end -%>
				<% if flash[:notice] -%>
				<div class="alert alert-success">
					<button type="button" class="close" data-dismiss="alert">
						&times;
					</button>
					<p class='error'>
						<%= h flash[:notice] %>
					</p>
				</div>

				<% end -%>
				<%= yield%>

			</div>
			<div class="span4 pull-right">

				<div class="well">
					<div class="frm">
						<h2>Login</h2>
						<%= form_for("user", :url=>user_session_path,:class=>"form-vertical") do |f|%>
						<div>

							<%= f.text_field :email, :placeholder=>"Email", :autofocus => true%>
						</div>
						<div>
							<%= f.password_field :password, :placeholder =>"password"%>
						</div>

						<div>
							<%= f.submit "Sign in", :class=>"btn"%>
							<%= link_to "Forgot Your Password", new_password_path('user')%>
						</div>

						<%end%>
					</div>
				</div>
				<div class="span4 pull-right">
					<div class="cat">

						Category
					</div>
					<div class="catinner">
						<ul class="navlist">
							<li>
								<a href="#"> Familly </a>
							</li>
							<li>
								<a href="#"> Programming </a>
							</li>
							<li>
								<a href="#"> Relationship</a>
							</li>
							<li>
								<a href="#"> Familly </a>
							</li>
							<li>
								<a href="#"> Familly </a>
							</li>
							</u>
					</div>
				</div>

			</div>

		</div>
		<div class="footer">
			<div class="container">
				<p>sdgjdsgjdgskjdgskjdgsnngklsganklgbasng</p>
				<div class="social">
						<%= image_tag("facebook.png")%>
					
						<%= image_tag("twitter.png")%>	
						<%= image_tag("rss.png")%>				

			</div>
		</div>

	</body>
</html>

My Documents/Aptana Studio 3 Workspace/Portfolio/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  
   
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div>
   <%= render :partial => 'tags/form',
             :locals => {:form => post_form} %>
      </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

My Documents/Aptana Studio 3 Workspace/Portfolio/app/views/posts/_post.html.erb
<%= div_for post do%>

	<h3> <%= post.title %></h3>
	<hr/>
	<p>
		<%= post.content %>
		<%= @post.user.first_name%>
	</p>
	<div class="meta">
		<%= link_to time_ago_in_words(post.created_at) +" ago", post %> 

		<span class="admin"><%= link_to 'Edit', edit_post_path(post) %></span>
		<span class="admin"><%= link_to 'Destroy', post, method: :delete, remote: true %></span>
	</div>
	
	<%end%>

My Documents/Aptana Studio 3 Workspace/Portfolio/app/views/posts/destroy.js.erb
$("#<%= dom_id(@post) %>").fadeOut();

My Documents/Aptana Studio 3 Workspace/Portfolio/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

My Documents/Aptana Studio 3 Workspace/Portfolio/app/views/posts/index.html.erb
<h1>All posts</h1>

<% @posts.each do |post| %>
<div class ="page-header">
	<%= div_for post do %>

	<h3> <%= post.title %></h3>
	<%= post.comments.count %>
	<hr/>
	<p>
		<%= post.content %><br/>
		<!--<%=post.user.full_name%></b>-->
	</p>
	<div class="meta">
		<%= link_to time_ago_in_words(post.created_at) +" ago", post %>

		<span class="admin"><%= link_to 'Edit', edit_post_path(post) %></span>
		<span class="admin"><%= link_to 'Destroy', post, method: :delete, remote: true %></span>
	</div>

	<%end%>
</div>
<% end %>
<%= will_paginate @posts %>

<%= link_to 'New Post', new_post_path, :class=>'btn btn-success' %>

My Documents/Aptana Studio 3 Workspace/Portfolio/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

My Documents/Aptana Studio 3 Workspace/Portfolio/app/views/posts/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<h1> <%= @post.title %></h1>
<hr/>
<p>

	<%= @post.content %>
	
</p>
 
<p>
  <b>Tags:</b>
  <%= join_tags(@post) %>
</p>
 
<%=render @post.comments%>

<%= render "comments/form" %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>